// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokerGameRSF;

#nullable disable

namespace PokerGameRSF.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PokerGame.Models.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CurrentBet")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("CurrentTurnPlayerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<Guid>("Player1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Player2Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Pot")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("WinningCombination")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTurnPlayerId");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("WinnerId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("PokerGame.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Chips")
                        .HasColumnType("numeric");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PokerGameRSF.Models.Bet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("PokerGameRSF.Models.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("Suit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("PokerGameRSF.Models.PlayerAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BetId")
                        .IsUnique();

                    b.HasIndex("GameSessionId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1")
                        .IsUnique();

                    b.ToTable("PlayerActions");
                });

            modelBuilder.Entity("PokerGameRSF.Models.PlayerCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsInHand")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("UserId");

                    b.HasIndex("GameSessionId", "UserId");

                    b.ToTable("PlayerCards");
                });

            modelBuilder.Entity("PokerGame.Models.GameSession", b =>
                {
                    b.HasOne("PokerGame.Models.User", "CurrentTurnPlayer")
                        .WithMany()
                        .HasForeignKey("CurrentTurnPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokerGame.Models.User", "Player1")
                        .WithMany("GameSessionsAsPlayer1")
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokerGame.Models.User", "Player2")
                        .WithMany("GameSessionsAsPlayer2")
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokerGame.Models.User", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentTurnPlayer");

                    b.Navigation("Player1");

                    b.Navigation("Player2");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("PokerGameRSF.Models.Bet", b =>
                {
                    b.HasOne("PokerGame.Models.GameSession", "GameSession")
                        .WithMany("Bets")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokerGame.Models.User", "User")
                        .WithMany("Bets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PokerGameRSF.Models.PlayerAction", b =>
                {
                    b.HasOne("PokerGameRSF.Models.Bet", "Bet")
                        .WithOne()
                        .HasForeignKey("PokerGameRSF.Models.PlayerAction", "BetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokerGame.Models.GameSession", "GameSession")
                        .WithMany("PlayerActions")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokerGame.Models.User", "User")
                        .WithMany("PlayerActions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokerGame.Models.User", null)
                        .WithOne("PlayerAction")
                        .HasForeignKey("PokerGameRSF.Models.PlayerAction", "UserId1");

                    b.Navigation("Bet");

                    b.Navigation("GameSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PokerGameRSF.Models.PlayerCard", b =>
                {
                    b.HasOne("PokerGameRSF.Models.Card", "Card")
                        .WithMany("PlayerCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokerGame.Models.GameSession", "GameSession")
                        .WithMany("PlayerCards")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokerGame.Models.User", "User")
                        .WithMany("PlayerCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Card");

                    b.Navigation("GameSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PokerGame.Models.GameSession", b =>
                {
                    b.Navigation("Bets");

                    b.Navigation("PlayerActions");

                    b.Navigation("PlayerCards");
                });

            modelBuilder.Entity("PokerGame.Models.User", b =>
                {
                    b.Navigation("Bets");

                    b.Navigation("GameSessionsAsPlayer1");

                    b.Navigation("GameSessionsAsPlayer2");

                    b.Navigation("PlayerAction")
                        .IsRequired();

                    b.Navigation("PlayerActions");

                    b.Navigation("PlayerCards");
                });

            modelBuilder.Entity("PokerGameRSF.Models.Card", b =>
                {
                    b.Navigation("PlayerCards");
                });
#pragma warning restore 612, 618
        }
    }
}
